---
# tasks file for telegraf
- name: Add InfluxDB repository file [RHEL/CentOS]
  template:
    src: influxdb.repo.j2
    dest: /etc/yum.repos.d/influxdb.repo
    force: yes
    backup: yes

- name: install telegraf
  yum:
    name: telegraf
    state: latest
  notify: restart telegraf

- name: configure telegraf
  template:
    src: telegraf.conf.j2
    dest: /etc/telegraf/telegraf.conf
  notify: restart telegraf

- name: start telegraf
  service:
    name: telegraf
    state: started
    enabled: yes
